// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 14.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Genie.Templates.Infrastructure.Models
{
    using Genie.Base;
    using Genie.Extensions;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    public partial class Relation : RelationBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("using System;\r\nusing System.Data;\r\nusing System.Linq;\r\nusing System.Collections.G" +
                    "eneric;\r\nusing ");
            
            #line 8 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerationContext.BaseNamespace));
            
            #line default
            #line hidden
            this.Write(".Infrastructure.Repositories;\r\nusing ");
            
            #line 9 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerationContext.BaseNamespace));
            
            #line default
            #line hidden
            this.Write(".Dapper;\r\nusing ");
            
            #line 10 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerationContext.BaseNamespace));
            
            #line default
            #line hidden
            this.Write(".Infrastructure.Interfaces;\r\nusing ");
            
            #line 11 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerationContext.BaseNamespace));
            
            #line default
            #line hidden
            this.Write(".Infrastructure.Models.Abstract;\r\nusing ");
            
            #line 12 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerationContext.BaseNamespace));
            
            #line default
            #line hidden
            this.Write(".Infrastructure.Filters.Abstract;\r\nusing ");
            
            #line 13 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerationContext.BaseNamespace));
            
            #line default
            #line hidden
            this.Write(".Infrastructure.Filters.Concrete;\r\nusing ");
            
            #line 14 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerationContext.BaseNamespace));
            
            #line default
            #line hidden
            this.Write(".Infrastructure.Models.Concrete;\r\nusing ");
            
            #line 15 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerationContext.BaseNamespace));
            
            #line default
            #line hidden
            this.Write(".Infrastructure.Repositories.Abstract;\r\n\r\n");
            
            #line 17 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
var entity = _relation;
var name = _relation.Name;

            
            #line default
            #line hidden
            this.Write("namespace ");
            
            #line 20 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerationContext.BaseNamespace));
            
            #line default
            #line hidden
            this.Write(".Infrastructure.Models\r\n{\r\n    namespace Abstract\r\n    {\r\n\t    public interface I" +
                    "");
            
            #line 24 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write("QueryContext\r\n\t    {\r\n            I");
            
            #line 26 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write("QueryContext Page(int pageSize, int page);\r\n            I");
            
            #line 27 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write("QueryContext Top(int limit);\r\n            I");
            
            #line 28 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write("QueryContext Skip(int skip);\r\n            I");
            
            #line 29 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write("QueryContext Take(int take);\r\n\t\t    I");
            
            #line 30 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write("FilterContext Where { get; }\r\n\t\t    I");
            
            #line 31 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write("OrderContext OrderBy { get; }\r\n\t        IEnumerable<");
            
            #line 32 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write("> Query(IDbTransaction transaction = null);\r\n\t        int Count(IDbTransaction tr" +
                    "ansaction = null);\r\n\t    }\r\n\r\n\t    public interface I");
            
            #line 36 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write("FilterContext : IFilterContext\r\n\t    {\r\n");
            
            #line 38 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
foreach(var atd in entity.Attributes){
            
            #line default
            #line hidden
            
            #line 39 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
if(atd.DataType == "string"){
            
            #line default
            #line hidden
            this.Write("\t\t    IStringFilter<I");
            
            #line 40 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write("FilterContext,I");
            
            #line 40 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write("QueryContext> ");
            
            #line 40 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(atd.Name));
            
            #line default
            #line hidden
            this.Write(" { get; }\r\n");
            
            #line 41 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
} else if(atd.DataType == "int" || atd.DataType == "int?" || atd.DataType == "double" || atd.DataType == "double?" || atd.DataType == "decimal" || atd.DataType == "decimal?" || atd.DataType == "long" || atd.DataType == "long?" ){
            
            #line default
            #line hidden
            this.Write("\t\t    INumberFilter<I");
            
            #line 42 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write("FilterContext,I");
            
            #line 42 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write("QueryContext> ");
            
            #line 42 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(atd.Name));
            
            #line default
            #line hidden
            this.Write(" { get; }\r\n");
            
            #line 43 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
}else if(atd.DataType == "DateTime" || atd.DataType == "DateTime?"){
            
            #line default
            #line hidden
            this.Write("\t\t    IDateFilter<I");
            
            #line 44 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write("FilterContext,I");
            
            #line 44 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write("QueryContext> ");
            
            #line 44 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(atd.Name));
            
            #line default
            #line hidden
            this.Write(" { get; }\r\n");
            
            #line 45 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
}else if(atd.DataType == "bool" || atd.DataType == "bool?"){
            
            #line default
            #line hidden
            this.Write("\t\t    IBoolFilter<I");
            
            #line 46 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write("FilterContext,I");
            
            #line 46 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write("QueryContext> ");
            
            #line 46 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(atd.Name));
            
            #line default
            #line hidden
            this.Write(" { get; }\r\n");
            
            #line 47 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
}
            
            #line default
            #line hidden
            
            #line 48 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
}
            
            #line default
            #line hidden
            this.Write("\t    }\r\n\r\n        public interface I");
            
            #line 51 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write("OrderContext: IOrderContext\r\n        {\r\n");
            
            #line 53 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
foreach(var atd in entity.Attributes){
            
            #line default
            #line hidden
            this.Write("\t\t    IOrderElement<I");
            
            #line 54 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write("OrderContext,I");
            
            #line 54 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write("QueryContext> ");
            
            #line 54 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(atd.Name));
            
            #line default
            #line hidden
            this.Write(" { get; }\r\n");
            
            #line 55 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
}
            
            #line default
            #line hidden
            this.Write("        }\r\n    }\r\n    \r\n    namespace Concrete\r\n    {\r\n        [Table(\"[dbo].[");
            
            #line 61 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write("]\")]\r\n        public class ");
            
            #line 62 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write(" : BaseModel\r\n        {\r\n");
            
            #line 64 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
foreach(var atd in entity.Attributes){
            
            #line default
            #line hidden
            this.Write("\t\t    private ");
            
            #line 65 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(atd.DataType));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 65 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(atd.FieldName));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 66 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
}
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 68 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
foreach(var atd in
 entity.ForeignKeyAttributes){
            
            #line default
            #line hidden
            this.Write("\t\t    private ");
            
            #line 70 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(atd.ReferencingRelationName));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 70 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(atd.ReferencingNonForeignKeyAttribute.FieldName));
            
            #line default
            #line hidden
            this.Write("Obj;\r\n");
            
            #line 71 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
}
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 73 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
foreach(var atd in entity.Attributes){
            
            #line default
            #line hidden
            
            #line 74 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
	if(atd.IsKey) {
            
            #line default
            #line hidden
            this.Write("\t\t    [Key]\r\n");
            
            #line 76 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
	}
            
            #line default
            #line hidden
            this.Write("\t\t    public ");
            
            #line 77 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(atd.DataType));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 77 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(atd.Name));
            
            #line default
            #line hidden
            this.Write(" { get { return ");
            
            #line 77 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(atd.FieldName));
            
            #line default
            #line hidden
            this.Write("; } set { if(");
            
            #line 77 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(atd.FieldName));
            
            #line default
            #line hidden
            this.Write(" == value ) { return; }  ");
            
            #line 77 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(atd.FieldName));
            
            #line default
            #line hidden
            this.Write(" = value; __Updated(\"");
            
            #line 77 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(atd.Name));
            
            #line default
            #line hidden
            this.Write("\"); ");
            
            #line 77 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(atd.RefPropName != null ? atd.RefPropName + " = null;" : ""));
            
            #line default
            #line hidden
            this.Write(" } }\r\n");
            
            #line 78 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
}
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 80 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
foreach(var atd in entity.ForeignKeyAttributes){
            
            #line default
            #line hidden
            this.Write("\t\t    public ");
            
            #line 81 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(atd.ReferencingRelationName));
            
            #line default
            #line hidden
            this.Write(" Get");
            
            #line 81 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(atd.ReferencingNonForeignKeyAttribute.Name));
            
            #line default
            #line hidden
            this.Write("(IDbTransaction transaction =null)\r\n            {\r\n                return Databas" +
                    "eUnitOfWork != null ? ");
            
            #line 83 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(atd.ReferencingNonForeignKeyAttribute.FieldName));
            
            #line default
            #line hidden
            this.Write("Obj ?? (");
            
            #line 83 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(atd.ReferencingNonForeignKeyAttribute.FieldName));
            
            #line default
            #line hidden
            this.Write("Obj = DatabaseUnitOfWork.");
            
            #line 83 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(atd.ReferencingRelationName));
            
            #line default
            #line hidden
            this.Write("Repository.Get().Where.");
            
            #line 83 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(atd.ReferencingTableColumnName));
            
            #line default
            #line hidden
            this.Write(".Equals(");
            
            #line 83 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(atd.ReferencingNonForeignKeyAttribute.FieldName));
            
            #line default
            #line hidden
            
            #line 83 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(atd.ReferencingNonForeignKeyAttribute.DataType.EndsWith("?") ?  ".GetValueOrDefault()" : ""));
            
            #line default
            #line hidden
            this.Write(").Filter().Top(1).Query(transaction).FirstOrDefault()) : null;\r\n            }\r\n");
            
            #line 85 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
}
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 87 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
foreach(var list in entity.ReferenceLists){
            
            #line default
            #line hidden
            this.Write("\t\t    public IEnumerable<");
            
            #line 88 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(list.ReferncedRelationName));
            
            #line default
            #line hidden
            this.Write("> ");
            
            #line 88 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(list.ReferncedRelationName.ToPlural()));
            
            #line default
            #line hidden
            this.Write("WhereThisIs");
            
            #line 88 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(list.ReferencedPropertyName));
            
            #line default
            #line hidden
            this.Write("(IDbTransaction transaction = null ){ return DatabaseUnitOfWork.");
            
            #line 88 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(list.ReferncedRelationName));
            
            #line default
            #line hidden
            this.Write("Repository.Get().Where.");
            
            #line 88 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(list.ReferencedPropertyName));
            
            #line default
            #line hidden
            this.Write(".Equals(");
            
            #line 88 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(list.ReferencedPropertyOnThisRelation));
            
            #line default
            #line hidden
            this.Write(").Filter().Query(transaction); }\r\n");
            
            #line 89 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
}
            
            #line default
            #line hidden
            this.Write("        }\r\n\r\n\t    internal class ");
            
            #line 92 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write("QueryContext: I");
            
            #line 92 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write("QueryContext\r\n\t    {\r\n\t\t    private I");
            
            #line 94 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write("FilterContext _where; \r\n\t        private I");
            
            #line 95 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write("OrderContext _order;\r\n\t\t    private readonly I");
            
            #line 96 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write("Repository _repo;\r\n\r\n            private int? _page;\r\n            private int? _p" +
                    "ageSize;\r\n            private int? _limit;\r\n            private int? _skip;\r\n   " +
                    "         private int? _take;\r\n\r\n            public I");
            
            #line 104 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write("QueryContext Page(int pageSize, int page)\r\n            {\r\n                _page =" +
                    " page;\r\n                _pageSize = pageSize;\r\n                return this;\r\n   " +
                    "         }\r\n\r\n            public I");
            
            #line 111 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write("QueryContext Top(int limit)\r\n            {\r\n                _limit = limit;\r\n    " +
                    "            return this;\r\n            }\r\n\r\n            public I");
            
            #line 117 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write("QueryContext Skip(int skip)\r\n            {\r\n                _skip = skip;\r\n      " +
                    "          return this;\r\n            }\r\n\r\n            public I");
            
            #line 123 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write("QueryContext Take(int take)\r\n            {\r\n                _take = take;\r\n      " +
                    "          return this;\r\n            }\r\n\t\t\r\n\t\t    internal ");
            
            #line 129 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write("QueryContext(I");
            
            #line 129 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write("Repository repo) { _repo = repo; }\r\n\t\t\r\n\t\t    public I");
            
            #line 131 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write("FilterContext Where { get { return _where ?? (_where = new ");
            
            #line 131 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write("FilterContext(this)); }}\r\n        \r\n\t\t    public I");
            
            #line 133 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write("OrderContext OrderBy { get { return _order ?? (_order = new ");
            
            #line 133 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write("OrderContext(this)); } }\r\n\r\n            public IEnumerable<");
            
            #line 135 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write(@"> Query(IDbTransaction transaction = null)
	        {
	            return _repo.Get(GetQuery(transaction));
	        }

	        public int Count(IDbTransaction transaction = null)
	        {
                return _repo.Count(GetQuery(transaction));
	        }

	        private IRepoQuery GetQuery(IDbTransaction transaction)
	        {
	            return new RepoQuery
	            {
	                Target = ""[dbo].[");
            
            #line 149 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write(@"]"",
	                Where = _where?.GetFilterExpressions(),
	                Order = _order?.GetOrderExpressions(),
	                PageSize = _pageSize,
	                Page = _page,
	                Limit = _limit,
	                Skip = _skip,
	                Take = _take,
	                Transaction = transaction
	            };
	        }
	    }

	    internal class ");
            
            #line 162 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write("FilterContext : BaseFilterContext, I");
            
            #line 162 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write("FilterContext \r\n\t    {\r\n\t\t    private readonly I");
            
            #line 164 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write("QueryContext  _queryContext;\r\n\t\t    internal ");
            
            #line 165 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write("FilterContext(");
            
            #line 165 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write("QueryContext context) { _queryContext = context; }\r\n\r\n");
            
            #line 167 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
foreach(var atd in entity.Attributes){
            
            #line default
            #line hidden
            
            #line 168 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
if(atd.DataType == "string"){
            
            #line default
            #line hidden
            this.Write("\t\t    private IStringFilter<I");
            
            #line 169 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write("FilterContext, I");
            
            #line 169 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write("QueryContext> ");
            
            #line 169 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(atd.FieldName));
            
            #line default
            #line hidden
            this.Write(";\r\n\t\t    public IStringFilter<I");
            
            #line 170 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write("FilterContext, I");
            
            #line 170 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write("QueryContext> ");
            
            #line 170 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(atd.Name));
            
            #line default
            #line hidden
            this.Write(" { get { return ");
            
            #line 170 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(atd.FieldName));
            
            #line default
            #line hidden
            this.Write(" ?? ( ");
            
            #line 170 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(atd.FieldName));
            
            #line default
            #line hidden
            this.Write(" = new StringFilter<I");
            
            #line 170 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write("FilterContext, I");
            
            #line 170 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write("QueryContext>(\"");
            
            #line 170 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(atd.Name));
            
            #line default
            #line hidden
            this.Write("\", this, _queryContext)); } }\r\n");
            
            #line 171 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
} else if(atd.DataType == "int" || atd.DataType == "int?" || atd.DataType == "double" || atd.DataType == "double?" || atd.DataType == "decimal" || atd.DataType == "decimal?" || atd.DataType == "long" || atd.DataType == "long?" ){
            
            #line default
            #line hidden
            this.Write("\t\t    private INumberFilter<I");
            
            #line 172 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write("FilterContext, I");
            
            #line 172 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write("QueryContext> ");
            
            #line 172 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(atd.FieldName));
            
            #line default
            #line hidden
            this.Write(";\r\n\t\t    public INumberFilter<I");
            
            #line 173 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write("FilterContext, I");
            
            #line 173 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write("QueryContext> ");
            
            #line 173 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(atd.Name));
            
            #line default
            #line hidden
            this.Write(" { get { return ");
            
            #line 173 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(atd.FieldName));
            
            #line default
            #line hidden
            this.Write(" ?? ( ");
            
            #line 173 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(atd.FieldName));
            
            #line default
            #line hidden
            this.Write(" = new NumberFilter<I");
            
            #line 173 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write("FilterContext, I");
            
            #line 173 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write("QueryContext>(\"");
            
            #line 173 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(atd.Name));
            
            #line default
            #line hidden
            this.Write("\", this, _queryContext)); } }\r\n");
            
            #line 174 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
}else if(atd.DataType == "DateTime" || atd.DataType == "DateTime?"){
            
            #line default
            #line hidden
            this.Write("    \t    private IDateFilter<I");
            
            #line 175 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write("FilterContext, I");
            
            #line 175 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write("QueryContext> ");
            
            #line 175 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(atd.FieldName));
            
            #line default
            #line hidden
            this.Write(";\r\n\t\t    public IDateFilter<I");
            
            #line 176 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write("FilterContext, I");
            
            #line 176 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write("QueryContext> ");
            
            #line 176 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(atd.Name));
            
            #line default
            #line hidden
            this.Write(" { get { return ");
            
            #line 176 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(atd.FieldName));
            
            #line default
            #line hidden
            this.Write(" ?? ( ");
            
            #line 176 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(atd.FieldName));
            
            #line default
            #line hidden
            this.Write(" = new DateFilter<I");
            
            #line 176 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write("FilterContext, I");
            
            #line 176 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write("QueryContext>(\"");
            
            #line 176 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(atd.Name));
            
            #line default
            #line hidden
            this.Write("\", this, _queryContext)); } }\r\n");
            
            #line 177 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
}else if(atd.DataType == "bool" || atd.DataType == "bool?"){
            
            #line default
            #line hidden
            this.Write("    \t    private IBoolFilter<I");
            
            #line 178 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write("FilterContext, I");
            
            #line 178 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write("QueryContext> ");
            
            #line 178 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(atd.FieldName));
            
            #line default
            #line hidden
            this.Write(";\r\n\t\t    public IBoolFilter<I");
            
            #line 179 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write("FilterContext, I");
            
            #line 179 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write("QueryContext> ");
            
            #line 179 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(atd.Name));
            
            #line default
            #line hidden
            this.Write(" { get { return ");
            
            #line 179 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(atd.FieldName));
            
            #line default
            #line hidden
            this.Write(" ?? ( ");
            
            #line 179 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(atd.FieldName));
            
            #line default
            #line hidden
            this.Write(" = new BoolFilter<I");
            
            #line 179 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write("FilterContext, I");
            
            #line 179 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write("QueryContext>(\"");
            
            #line 179 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(atd.Name));
            
            #line default
            #line hidden
            this.Write("\", this, _queryContext)); } }\r\n");
            
            #line 180 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
}
            
            #line default
            #line hidden
            
            #line 181 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
}
            
            #line default
            #line hidden
            this.Write("\t    }\r\n\r\n        public class  ");
            
            #line 184 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write("OrderContext : BaseOrderContext, I");
            
            #line 184 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write("OrderContext\r\n        {\r\n\t\t    private readonly I");
            
            #line 186 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write("QueryContext  _queryContext;\r\n\t\t    internal ");
            
            #line 187 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write("OrderContext(I");
            
            #line 187 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write("QueryContext context) { _queryContext = context; }\r\n\r\n");
            
            #line 189 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
foreach(var atd in entity.Attributes){
            
            #line default
            #line hidden
            this.Write("            private IOrderElement<I");
            
            #line 190 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write("OrderContext, I");
            
            #line 190 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write("QueryContext> ");
            
            #line 190 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(atd.FieldName));
            
            #line default
            #line hidden
            this.Write(";\r\n\t\t    public IOrderElement<I");
            
            #line 191 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write("OrderContext, I");
            
            #line 191 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write("QueryContext> ");
            
            #line 191 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(atd.Name));
            
            #line default
            #line hidden
            this.Write(" { get { return ");
            
            #line 191 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(atd.FieldName));
            
            #line default
            #line hidden
            this.Write(" ?? ( ");
            
            #line 191 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(atd.FieldName));
            
            #line default
            #line hidden
            this.Write(" = new OrderElement<I");
            
            #line 191 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write("OrderContext, I");
            
            #line 191 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write("QueryContext>(\"");
            
            #line 191 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(atd.Name));
            
            #line default
            #line hidden
            this.Write("\", this, _queryContext)); } }\r\n");
            
            #line 192 "D:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
}
            
            #line default
            #line hidden
            this.Write("        }\r\n    }\r\n}\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    public class RelationBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
