// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 14.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Genie.Templates.Infrastructure.Models
{
    using Genie.Base;
    using Genie.Extensions;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "F:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    public partial class Relation : RelationBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("using System;\r\nusing System.Data;\r\nusing System.Linq;\r\nusing System.Collections.G" +
                    "eneric;\r\nusing ");
            
            #line 8 "F:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerationContext.BaseNamespace));
            
            #line default
            #line hidden
            this.Write(".Infrastructure.Repositories;\r\nusing ");
            
            #line 9 "F:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerationContext.BaseNamespace));
            
            #line default
            #line hidden
            this.Write(".Dapper;\r\nusing ");
            
            #line 10 "F:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerationContext.BaseNamespace));
            
            #line default
            #line hidden
            this.Write(".Infrastructure.Interfaces;\r\nusing ");
            
            #line 11 "F:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerationContext.BaseNamespace));
            
            #line default
            #line hidden
            this.Write(".Infrastructure.Filters;\r\n\r\n");
            
            #line 13 "F:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
var entity = _relation;
            
            #line default
            #line hidden
            this.Write("namespace ");
            
            #line 14 "F:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerationContext.BaseNamespace));
            
            #line default
            #line hidden
            this.Write(".Infrastructure.Models\r\n{\r\n    [Table(\"[dbo].[");
            
            #line 16 "F:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("]\")]\r\n    public class ");
            
            #line 17 "F:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write(" : BaseModel\r\n    {\r\n");
            
            #line 19 "F:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
foreach(var atd in entity.Attributes){
            
            #line default
            #line hidden
            this.Write("\t\tprivate ");
            
            #line 20 "F:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(atd.DataType));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 20 "F:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(atd.FieldName));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 21 "F:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
}
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 23 "F:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
foreach(var atd in
 entity.ForeignKeyAttributes){
            
            #line default
            #line hidden
            this.Write("\t\tprivate ");
            
            #line 25 "F:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(atd.ReferencingRelationName));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 25 "F:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(atd.ReferencingNonForeignKeyAttribute.FieldName));
            
            #line default
            #line hidden
            this.Write("Obj;\r\n");
            
            #line 26 "F:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
}
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 28 "F:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
foreach(var atd in entity.Attributes){
            
            #line default
            #line hidden
            
            #line 29 "F:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
	if(atd.IsKey) {
            
            #line default
            #line hidden
            this.Write("\t\t[Key]\r\n");
            
            #line 31 "F:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
	}
            
            #line default
            #line hidden
            this.Write("\t\tpublic ");
            
            #line 32 "F:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(atd.DataType));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 32 "F:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(atd.Name));
            
            #line default
            #line hidden
            this.Write(" { get { return ");
            
            #line 32 "F:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(atd.FieldName));
            
            #line default
            #line hidden
            this.Write("; } set { ");
            
            #line 32 "F:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(atd.FieldName));
            
            #line default
            #line hidden
            this.Write(" = value; __Updated(\"");
            
            #line 32 "F:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(atd.Name));
            
            #line default
            #line hidden
            this.Write("\"); } }\r\n");
            
            #line 33 "F:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
}
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 35 "F:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
foreach(var atd in entity.ForeignKeyAttributes){
            
            #line default
            #line hidden
            this.Write("\t\tpublic ");
            
            #line 36 "F:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(atd.ReferencingRelationName));
            
            #line default
            #line hidden
            this.Write(" Get");
            
            #line 36 "F:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(atd.ReferencingNonForeignKeyAttribute.Name));
            
            #line default
            #line hidden
            this.Write("(IDbTransaction transaction =null)\r\n        {\r\n            return DatabaseUnitOfW" +
                    "ork != null ? ");
            
            #line 38 "F:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(atd.ReferencingNonForeignKeyAttribute.FieldName));
            
            #line default
            #line hidden
            this.Write("Obj ?? (");
            
            #line 38 "F:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(atd.ReferencingNonForeignKeyAttribute.FieldName));
            
            #line default
            #line hidden
            this.Write("Obj = DatabaseUnitOfWork.");
            
            #line 38 "F:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(atd.ReferencingRelationName));
            
            #line default
            #line hidden
            this.Write("Repository.Get().Where.");
            
            #line 38 "F:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(atd.ReferencingTableColumnName));
            
            #line default
            #line hidden
            this.Write(".Equals(");
            
            #line 38 "F:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(atd.ReferencingNonForeignKeyAttribute.FieldName));
            
            #line default
            #line hidden
            
            #line 38 "F:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(atd.ReferencingNonForeignKeyAttribute.DataType.EndsWith("?") ?  ".GetValueOrDefault()" : ""));
            
            #line default
            #line hidden
            this.Write(").Filter().Top(1).Query(transaction).FirstOrDefault()) : null;\r\n        }\r\n");
            
            #line 40 "F:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
}
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 42 "F:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
foreach(var list in entity.ReferenceLists){
            
            #line default
            #line hidden
            this.Write("\t\tpublic IEnumerable<");
            
            #line 43 "F:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(list.ReferncedRelationName));
            
            #line default
            #line hidden
            this.Write("> ");
            
            #line 43 "F:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(list.ReferncedRelationName.ToPlural()));
            
            #line default
            #line hidden
            this.Write("WhereThisIs");
            
            #line 43 "F:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(list.ReferencedPropertyName));
            
            #line default
            #line hidden
            this.Write("(IDbTransaction transaction = null ){ return DatabaseUnitOfWork.");
            
            #line 43 "F:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(list.ReferncedRelationName));
            
            #line default
            #line hidden
            this.Write("Repository.Get().Where.");
            
            #line 43 "F:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(list.ReferencedPropertyName));
            
            #line default
            #line hidden
            this.Write(".Equals(");
            
            #line 43 "F:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(list.ReferencedPropertyOnThisRelation));
            
            #line default
            #line hidden
            this.Write(").Filter().Query(transaction); }\r\n");
            
            #line 44 "F:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
}
            
            #line default
            #line hidden
            this.Write("    }\r\n\r\n\tpublic class ");
            
            #line 47 "F:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("QueryContext \r\n\t{\r\n\t\tprivate ");
            
            #line 49 "F:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("FilterContext _where; \r\n\t    private ");
            
            #line 50 "F:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("OrderContext _order;\r\n\t\tprivate readonly ");
            
            #line 51 "F:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("Repository _repo;\r\n\t\tinternal ");
            
            #line 52 "F:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("QueryContext(");
            
            #line 52 "F:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("Repository repo) { _repo = repo; }\r\n\t\tpublic ");
            
            #line 53 "F:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("FilterContext Where { get { return _where ?? (_where = new ");
            
            #line 53 "F:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("FilterContext(this)); }}\r\n        public ");
            
            #line 54 "F:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("OrderContext OrderBy { get { return _order ?? (_order = new ");
            
            #line 54 "F:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("OrderContext(this)); } }\r\n\t    private int? _page;\r\n\t    private int? _pageSize;\r" +
                    "\n\t    private int? _limit;\r\n\t\tprivate int? _skip;\r\n\t\tprivate int? _take;\r\n\r\n    " +
                    "    public ");
            
            #line 61 "F:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("QueryContext Page(int pageSize, int page)\r\n        {\r\n            _page = page;\r\n" +
                    "            _pageSize = pageSize;\r\n            return this;\r\n        }\r\n\r\n      " +
                    "  public ");
            
            #line 68 "F:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("QueryContext Top(int limit)\r\n        {\r\n            _limit = limit;\r\n            " +
                    "return this;\r\n        }\r\n\r\n\t\tpublic ");
            
            #line 74 "F:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("QueryContext Skip(int skip)\r\n\t    {\r\n\t        _skip = skip;\r\n\t        return this" +
                    ";\r\n\t    }\r\n\r\n\t    public ");
            
            #line 80 "F:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("QueryContext Take(int take)\r\n\t    {\r\n\t        _take = take;\r\n\t        return this" +
                    ";\r\n\t    }\r\n\r\n\t    public IEnumerable<");
            
            #line 86 "F:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("> Query(IDbTransaction transaction = null)\r\n\t    {\r\n\t        return _repo.Get(\"[d" +
                    "bo].[");
            
            #line 88 "F:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("]\", _where?.GetFilterExpressions(), _order?.GetOrderExpressions(), _pageSize, _pa" +
                    "ge, _limit, _skip, _take, transaction);\r\n\t    }\r\n\t}\r\n\r\n\tpublic class ");
            
            #line 92 "F:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("FilterContext : BaseFilterContext\r\n\t{\r\n\t\tprivate readonly ");
            
            #line 94 "F:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("QueryContext  _queryContext;\r\n\t\tinternal ");
            
            #line 95 "F:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("FilterContext(");
            
            #line 95 "F:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("QueryContext context) { _queryContext = context; }\r\n\r\n");
            
            #line 97 "F:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
foreach(var atd in entity.Attributes){
            
            #line default
            #line hidden
            
            #line 98 "F:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
if(atd.DataType == "string"){
            
            #line default
            #line hidden
            this.Write("\t\tprivate StringFilter<");
            
            #line 99 "F:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("FilterContext,");
            
            #line 99 "F:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("QueryContext> ");
            
            #line 99 "F:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(atd.FieldName));
            
            #line default
            #line hidden
            this.Write(";\r\n\t\tpublic StringFilter<");
            
            #line 100 "F:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("FilterContext,");
            
            #line 100 "F:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("QueryContext> ");
            
            #line 100 "F:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(atd.Name));
            
            #line default
            #line hidden
            this.Write(" { get { return ");
            
            #line 100 "F:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(atd.FieldName));
            
            #line default
            #line hidden
            this.Write(" ?? ( ");
            
            #line 100 "F:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(atd.FieldName));
            
            #line default
            #line hidden
            this.Write(" = new StringFilter<");
            
            #line 100 "F:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("FilterContext,");
            
            #line 100 "F:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("QueryContext>(\"");
            
            #line 100 "F:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(atd.Name));
            
            #line default
            #line hidden
            this.Write("\", this, _queryContext)); } }\r\n");
            
            #line 101 "F:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
} else if(atd.DataType == "int" || atd.DataType == "int?" || atd.DataType == "double" || atd.DataType == "double?" || atd.DataType == "decimal" || atd.DataType == "decimal?" || atd.DataType == "long" || atd.DataType == "long?" ){
            
            #line default
            #line hidden
            this.Write("\t\tprivate NumberFilter<");
            
            #line 102 "F:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("FilterContext,");
            
            #line 102 "F:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("QueryContext> ");
            
            #line 102 "F:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(atd.FieldName));
            
            #line default
            #line hidden
            this.Write(";\r\n\t\tpublic NumberFilter<");
            
            #line 103 "F:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("FilterContext,");
            
            #line 103 "F:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("QueryContext> ");
            
            #line 103 "F:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(atd.Name));
            
            #line default
            #line hidden
            this.Write(" { get { return ");
            
            #line 103 "F:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(atd.FieldName));
            
            #line default
            #line hidden
            this.Write(" ?? ( ");
            
            #line 103 "F:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(atd.FieldName));
            
            #line default
            #line hidden
            this.Write(" = new NumberFilter<");
            
            #line 103 "F:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("FilterContext,");
            
            #line 103 "F:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("QueryContext>(\"");
            
            #line 103 "F:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(atd.Name));
            
            #line default
            #line hidden
            this.Write("\", this, _queryContext)); } }\r\n");
            
            #line 104 "F:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
}else if(atd.DataType == "DateTime" || atd.DataType == "DateTime?"){
            
            #line default
            #line hidden
            this.Write("    \tprivate DateFilter<");
            
            #line 105 "F:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("FilterContext,");
            
            #line 105 "F:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("QueryContext> ");
            
            #line 105 "F:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(atd.FieldName));
            
            #line default
            #line hidden
            this.Write(";\r\n\t\tpublic DateFilter<");
            
            #line 106 "F:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("FilterContext,");
            
            #line 106 "F:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("QueryContext> ");
            
            #line 106 "F:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(atd.Name));
            
            #line default
            #line hidden
            this.Write(" { get { return ");
            
            #line 106 "F:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(atd.FieldName));
            
            #line default
            #line hidden
            this.Write(" ?? ( ");
            
            #line 106 "F:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(atd.FieldName));
            
            #line default
            #line hidden
            this.Write(" = new DateFilter<");
            
            #line 106 "F:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("FilterContext,");
            
            #line 106 "F:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("QueryContext>(\"");
            
            #line 106 "F:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(atd.Name));
            
            #line default
            #line hidden
            this.Write("\", this, _queryContext)); } }\r\n");
            
            #line 107 "F:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
}
            
            #line default
            #line hidden
            
            #line 108 "F:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
}
            
            #line default
            #line hidden
            this.Write("\t}\r\n\r\n    public class  ");
            
            #line 111 "F:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("OrderContext : BaseOrderContext\r\n    {\r\n\t\tprivate readonly ");
            
            #line 113 "F:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("QueryContext  _queryContext;\r\n\t\tinternal ");
            
            #line 114 "F:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("OrderContext(");
            
            #line 114 "F:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("QueryContext context) { _queryContext = context; }\r\n\r\n");
            
            #line 116 "F:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
foreach(var atd in entity.Attributes){
            
            #line default
            #line hidden
            this.Write("        private OrderElement<");
            
            #line 117 "F:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("OrderContext,");
            
            #line 117 "F:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("QueryContext> ");
            
            #line 117 "F:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(atd.FieldName));
            
            #line default
            #line hidden
            this.Write(";\r\n\t\tpublic OrderElement<");
            
            #line 118 "F:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("OrderContext,");
            
            #line 118 "F:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("QueryContext> ");
            
            #line 118 "F:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(atd.Name));
            
            #line default
            #line hidden
            this.Write(" { get { return ");
            
            #line 118 "F:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(atd.FieldName));
            
            #line default
            #line hidden
            this.Write(" ?? ( ");
            
            #line 118 "F:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(atd.FieldName));
            
            #line default
            #line hidden
            this.Write(" = new OrderElement<");
            
            #line 118 "F:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("OrderContext,");
            
            #line 118 "F:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("QueryContext>(\"");
            
            #line 118 "F:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(atd.Name));
            
            #line default
            #line hidden
            this.Write("\", this, _queryContext)); } }\r\n");
            
            #line 119 "F:\Projects\Genie\Genie\Templates\Infrastructure\Models\Relation.tt"
}
            
            #line default
            #line hidden
            this.Write("    }\r\n}\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    public class RelationBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
